

<div class="page-header">

    <button aria-expanded="false" data-toggle="tab"  onclick="printsection('printableArea')" class="btn-new-mail no-border">
        <span class="btn btn-purple no-border">
            <i class="ace-icon fa fa-print bigger-130"></i>
            <span class="bigger-110">Print</span>
        </span>
    </button>
</div><!-- /.page-header -->


<div id="printableArea" class="print">
    <?php 
    $count=0;
    foreach($studentinfo as $info)
    {
        ++$count;
        ?>
        <div class="admitcarditem" style="<?php if($count%2==0){ echo 'page-break-after:always;';} ?>">
            <div class="instituteinfo">
                <div class="logo">
                    <img src="<?php echo base_url().$institute_details[0]['logo'];?>" height="70px" width="auto" alt="0"/>
                </div>
                <div class="title">
                 <h2 class="blue"><?php echo $institute_details[0]['instituteName'];?></h2>
             </div>
             <div class="subtitle">
                 <h3> <?php echo  $institute_details[0]['town'].", ".$institute_details[0]['city'].", ".$institute_details[0]['disname']; ?></h3>
             </div>       
         </div>
         <div class="year">
            <h4 class="green" >ADMIT CARD for&nbsp;<?php echo getSemesterName($semester_type);?><strong>-</strong><?php echo $other_basic_info[0]['session'];?></h4> 
        </div>
        <div class="examinfo">
            <strong class="blue">Class : </strong><strong><?php echo $other_basic_info[0]['programName'];?></strong class="blue"><strong>,</strong>&nbsp;
            <strong class="blue">Medium :</strong> <strong><?php echo $other_basic_info[0]['mediumName'];?></strong><strong>,</strong>&nbsp;
            <strong class="blue">Shift : </strong><strong><?php echo $other_basic_info[0]['shiftName'];?></strong><strong>,</strong>&nbsp;
            <strong class="blue">Group : </strong><strong><?php echo $other_basic_info[0]['groupName'];?></strong><strong>,</strong>&nbsp;
            <strong class="blue">Section  : </strong><strong><?php echo $other_basic_info[0]['sectionName'];?></strong>
        </div>
        <div class="routine">
         <div class="keynote">
            <table style="border-collapse: collapse">
               <caption style="text-align: center;"><b>EXAM ROUTINE</b></caption>
               <thead>
                <tr>
                    <th width="10%"><p class="blue">Date</p></th>
                    <th width="37%"><p class="blue">Subject Name</p></th>
                    <th width="10%"><p class="blue">Code</p></th>
                    <th width="13%"><p class="blue">Time</p></th>
                    <th width="8%"><p class="blue">Room</p></th>
                </tr>
            </thead>
            <tbody>
                <?php 
                foreach($exam_routine as $routine){?>
                   <tr>
                    <td> <?php echo $routine['date'];?></td>
                    <td><?php echo $routine['courseName'];?></td>
                    <td style="text-align: center;"> <?php echo $routine['courseCode'];?></td>
                    <td> <?php echo $routine['examtime'];?></td>
                    <td style="text-align: center;"><?php echo $routine['room'];?></td>
                </tr>
            <?php }
            ?>
        </tbody>
    </table>
    <div class="kenote-inner">
     <p class="red">Note: 1. Authority Holds full right to change exam routine as needed.</p>
     <p class="red last">     2. Admit Card is mandatory to Enter the Exam hall.</p>
 </div>
</div>

<div class="studentdetails">
 <div class="student-img">
   <img src="<?php echo base_url().$institute_details[0]['logo'];?>"/>
</div>
<div class="id">
    <span class="green">Id:&nbsp;<?php echo $info['studentId'];?></span>
</div>
<div class="name">
 <span class="blue"><?php echo $info['firstName'];?></span>
</div>
<div class="roll">
 <span class="red"><?php echo 'Roll No. '.$info['roll_no'];?></span>
</div>
</div>
<div style="clear: both;"></div>
</div>
<div class="signature">
    <table style="border-collapse: collapse;">
        <tbody>
            <tr>
                <td colspan="4"><img  src="http://localhost/aims/images/ct.png"> <br>.............................................<br>Class Teacher </td>
                <td style="vertical-align: bottom;"><h6> Admit Card generated by:&nbsp;&nbsp;<span>aims &nbsp;</span>||&nbsp; Powerd by:&nbsp;&nbsp;www.adventure-soft.com</h6></td>
                <td style="text-align: right;" colspan="4"><img src="http://localhost/aims/images/au.png"> <br>.............................................<br> Authorized Signature </td>
            </tr>
        </tbody>
    </table>
    
</div>
</div>
<?php } ?>
</div>









